### PR TITLE
A new RuleDB that forgets the strategy

### PR DESCRIPTION
**Pull request by enadeau**

### CODE REVIEW

**Comment by enadeau** [comment]
Yes I think we want the default the usual `RuleDB`. Maybe we add a flag the searcher `__init__` function to choose the rule db.

Before merging that we should also run some memory/time profiling to see what is the trade off.

**Comment by jaypantone** [comment]
I'd like to add a line in the RuleDBForgetStrategies status update that says how many times a strategy was recomputed. Thoughts?

**Comment by christianbean** [comment]
> I'd like to add a line in the RuleDBForgetStrategies status update that says how many times a strategy was recomputed. Thoughts?

this should be equivalent to `spec.number_of_rules()` if returning spec, else 0 throughout the run.

**Comment by jaypantone** [comment]
I agree that it should be, but it would be nice to have confirmation of that!

**Comment by enadeau** [comment]
We could do it while we are running the test, but we should not add it permanently as we would have an important memory footprint without bringing much value

**Comment by enadeau** [comment]
So I ran a quick test on one basis that uses reverse equivalence. I get a specification with 13 rules and the `__getitem__` methods on the rule dict is called 16 times.

I think this difference can be explained by two things:
1. Reverse equivalence require that we look the dict twice. I my example we looked the dict for the rules `(42, (35,))` and `(35, (42,))`
2. The specification contains 2 `EquivPathRules` that contain 3 combinatorial classes, i.e two rules

Hence, I think the class behaves as expected.

@christianbean is my reasoning correct?

**Comment by christianbean** [comment]
> So I ran a quick test on one basis that uses reverse equivalence. I get a specification with 13 rules and the `__getitem__` methods on the rule dict is called 16 times.
> 
> I think this difference can be explained by two things:
> 
> 1. Reverse equivalence require that we look the dict twice. I my example we looked the dict for the rules `(42, (35,))` and `(35, (42,))`
> 2. The specification contains 2 `EquivPathRules` that contain 3 combinatorial classes, i.e two rules
> 
> Hence, I think the class behaves as expected.
> 
> @christianbean is my reasoning correct?

Your reasoning is correct. There currently is no way to know in advance if it is forward or backwards as we lose this info when we put it into the equivdb.

**Comment by enadeau** [comment]
We just need to add the option to the css initializer and then it's ready to merge

**Pull request merged**
