### PR TITLE
Support multiple equation for maple equations

### PR DESCRIPTION
**Pull request by enadeau**
Now  the equation that are logged in look like
```
[I 200618 18:12:34 specification:259] # The system of 5 equations
    root_func := F[0, x]:
    eqs := [
    F[0, x] = (F[1, x] + F[2, x]),
    F[1, x] = (1),
    F[2, x] = F[3, x],
    F[3, x] = ((F[0, x]**(2)) * F[4, x]),
    F[4, x] = x
    ]:
    count := [1, 1, 2, 5, 14, 42, 132]:
```
 or if you have fusion
```
[I 200618 18:21:11 specification:260] # The system of 22 equations
    root_func := F[0, x]:
    eqs := [
    F[0, x] = (F[1, x] + F[2, x]),
    F[1, x] = (1),
    F[2, x] = F[3, x],
    F[3, x] = (F[4, x] * F[5, x]),
    F[4, x] = (F[6, x] + F[7, x]),
    F[5, x] = x,
    F[6, x] = (F[1, x] + F[8, x]),
    F[7, x] = F[10, x],
    F[8, x] = F[9, x],
    F[9, x] = (F[5, x] * F[6, x]),
    F[10, x] = (F[11, x] * (F[5, x] * F[6, x])),
    F[11, x] = NOTIMPLEMENTED,
    F[12, x, k[0]] = (F[13, x, k[0]] + F[14, x, k[0]]),
    F[13, x, k[0]] = (F[1, x] + F[15, x, k[0]]),
    F[14, x, k[0]] = F[19, x, k[0]],
    F[15, x, k[0]] = F[16, x, k[0]],
    F[16, x, k[0]] = NOTIMPLEMENTED,
    F[17, x, k[0], k[1]] = (F[13, x, k[1]] * F[18, x, k[0]]),
    F[18, x, k[0]] = NOTIMPLEMENTED,
    F[19, x, k[0]] = NOTIMPLEMENTED,
    F[20, x, k[0], k[1]] = (F[13, x, k[0]] * (F[21, x, k[1]] * F[5, x])),
    F[21, x, k[0]] = NOTIMPLEMENTED
    ]:
    count := [1, 1, 2, 5, 14, 42, 132]:
```

### CODE REVIEW

**Comment by christianbean** [comment]
I think it would be nicer if we only used the new format when the equations have multiple variable. 
This can be check with the line `any(rule.comb_class.extra_parameters for rule in self.rules_dict)` inside the specification class (in the maple_string method).

**Comment by ulfarsson** [comment]
The only thing that fails is pylint. I think it is unhappy here:
```python
    if isinstance(expr, sympy.core.symbol.Symbol):
         symb = str(expr)
         if "_" in symb:
             var, label = symb.split("_")
             return f"{var}[{label}]"
         else:
             return symb
     if expr.is_number:
         return f"({expr})"
     raise NotImplementedError(str(expr))
```

**Comment by enadeau** [comment]
> I think it would be nicer if we only used the new format when the equations have multiple variable.
> This can be check with the line `any(rule.comb_class.extra_parameters for rule in self.rules_dict)` inside the specification class (in the maple_string method).

I think we should be consistent and always use the same format. This way building pipeline is easier. I know the format is not pretty but keep in mind that this is not intended for human but for computer.

In the end we @jaypantone should probably get the final word has he's the one that knows maple.

**Comment by christianbean** [comment]
> > I think it would be nicer if we only used the new format when the equations have multiple variable.
> > This can be check with the line `any(rule.comb_class.extra_parameters for rule in self.rules_dict)` inside the specification class (in the maple_string method).
> 
> I think we should be consistent and always use the same format. This way building pipeline is easier. I know the format is not pretty but keep in mind that this is not intended for human but for computer.
> 
> In the end we @jaypantone should probably get the final word has he's the one that knows maple.

We also use it for a "pretty print" when logging what is sent to the solve method of sympy when using the get genf method.

**Comment by enadeau** [comment]
For the printing can I convince you to use `sympy.pretty` which gives systems like
```
F₀(x) = F₁(x) + F₂(x)
F₁(x) = 1
F₂(x) = F₃(x)
          2         
F₃(x) = F₀ (x)⋅F₄(x)
F₄(x) = x
```
Also can you tell me more about the tilescope failure? I don't see it on travis

**Comment by christianbean** [comment]
> For the printing can I convince you to use `sympy.pretty` which gives systems like
> 
> ```
> F₀(x) = F₁(x) + F₂(x)
> F₁(x) = 1
> F₂(x) = F₃(x)
>           2         
> F₃(x) = F₀ (x)⋅F₄(x)
> F₄(x) = x
> ```
> 
> Also can you tell me more about the tilescope failure? I don't see it on travis

I preferred the previous print. Also, it contradicts our demo video, which is a shame to do.

**Comment by enadeau** [comment]
I ran it locally and also reran the test on Travis (which depends on develop) and I can't get a failure

**Comment by christianbean** [comment]
> I ran it locally and also reran the test on Travis (which depends on develop) and I can't get a failure

I didn't have the requirements up to date, sorry!

**Comment by jaypantone** [comment]
Yeah I'm conflicted about which to show for non-fusion trees. In that case, I think the original equations look nicer (and the current pipeline is set up to use them, although it would be minor to change that). On the other hand, Émile makes a good point about consistency.

**Comment by jaypantone** [comment]
I don't like sympy's pretty-print because of the way it puts the exponent on a different line.

**Pull request merged**
