### PR TITLE
Add GC stats to status update when running with pypy

### PR DESCRIPTION
**Pull request by jaypantone**
Example of new status update below. If it's too long, let me know what lines you don't want to see.
```
[I 200514 13:38:10 comb_spec_searcher:526]
    Time taken so far is 592.4 seconds
    CSS status:
    	Total time accounted for is 567.0 seconds.
    	Applied queue 54516 times. Time spent is 0.95 seconds (~0%).
    	Applied one by one verification 10014 times. Time spent is 0.0 seconds (~0%).
    	Applied locally factorable verification 10007 times. Time spent is 0.0 seconds (~0%).
    	Applied row and column separation 13920 times. Time spent is 45.04 seconds (~7%).
    	Applied obstruction transitivity 16024 times. Time spent is 0.0 seconds (~0%).
    	Applied get specification 192 times. Time spent is 4.03 seconds (~0%).
    	Applied factor 7877 times. Time spent is 127.12 seconds (~22%).
    	Applied requirement corroboration 3017 times. Time spent is 0.0 seconds (~0%).
    	Applied row and column placement 257 times. Time spent is 389.54 seconds (~68%).
    	Applied is empty 7570 times. Time spent is 0.3 seconds (~0%).
    	Applied status 36 times. Time spent is 0.02 seconds (~0%).
    ClassDB status:
    	Total number of combinatorial classes found is 10014
    	Applied compress 19441 times. Time spent is 6.78 seconds.
    	Applied get label 19441 times. Time spent is 7.15 seconds.
    	Applied decompress 25072 times. Time spent is 6.6 seconds.
    	Applied get class 25072 times. Time spent is 6.7 seconds.
    	Applied is empty 5270 times. Time spent is 0.16 seconds
    Queue status:
    	Currently on 'level' 5
    	The size of the working queue is 16
    	The size of the current queue is 8
    	The size of the next queue is 9294
    	The number of times added to the next queue is 13038
    	The size of the current queues at each level: 0, 1, 4, 24, 236
    RuleDB status:
    	Total number of combinatorial rules is 9610
    Memory Status:
    	Total Memory OS has Allocated: 317 MiB
    	Current Memory Used: 122.9MB
    	Current Memory Allocated: 203.0MB
    	Current JIT Memory Used: 12.4MB
    	Current JIT Memory Allocated: 13.0MB
    	Peak Memory Used: 218.5MB
    	Peak Memory Allocated: 221.3MB
    	Total Garbage Collection Time: 39.27 seconds
```

### CODE REVIEW

**Comment by enadeau** [comment]
Looks nice! I think it could be merge as is but I'd prefer removing the JIT Memory stuff, I don't see it being useful.

I also wonder what is the difference between
```
Total Memory OS has Allocated: 317 MiB
Current Memory Allocated: 203.0MB
```
Is there a reason for the gap or it's just an other weirdness we can't explain?

**Comment by jaypantone** [comment]
> Looks nice! I think it could be merge as is but I'd prefer removing the JIT Memory stuff, I don't see it being useful.
> 
> I also wonder what is the difference between
> 
> ```
> Total Memory OS has Allocated: 317 MiB
> Current Memory Allocated: 203.0MB
> ```
> 
> Is there a reason for the gap or it's just an other weirdness we can't explain?

I can't really answer this. From the tiny bit I know, the way the OS decides to allocate memory is very complicated. This has some useful info: https://rushter.com/blog/python-memory-managment/

**Comment by jaypantone** [comment]
Don't merge this yet, I need to fix the fact that pypy prints the gc stats like "xMB" but we print total memory with the much nicer format "x MiB".

**Comment by jaypantone** [comment]
Made a few small changes in this most recent commit. Am I okay to merge?

**Comment by enadeau** [comment]
Do you mind moving the static method to  `utils.py` file? They don't really belongs to the css class

**Comment by enadeau** [comment]
I think I fixed the remaining issues. If test pass just do a squash and merge to keep the history clean.

**Comment by jaypantone** [comment]
Yes, thanks, I was going to point out that the next thing I'll add (in a new branch after this is merged) is using pympler to occasionally get memory usage of the CSS, and that will make that pylint error disappear anyway because it will need self.

**Pull request merged**
