### PR TITLE
Tidying up logging

### PR DESCRIPTION
**Pull request by christianbean**

### CODE REVIEW

**Comment by enadeau** [comment]
I disagree with the smallest logging being at the debug level since it won't be logged on any of the run that are significant. In my opinion it should stay at the info level so if a job hangs because of the smallest flag we would notice it by looking at the logs

**Comment by christianbean** [comment]
It makes for confusing print on master. I don't disagree with using it on our garpur runs.

**Comment by enadeau** [comment]
I think it will also be confusing for the user to see a job hang without any information if they use the smallest flag. I think that what we really is disable the logging when working on the expansion.

**Comment by christianbean** [comment]
We don't want to change the logging levels mid runs as this is a global setting. This can lead to unexpected behaviour, as we have previously seen.

We could log in the get_specifcation method "Searching for specification", and if SpecificationNotFound, log, "No specification found". This will increase the amount of logging considerable though.

**Pull request merged**
